BestOperator/urls.py
from django.conf.urls import url
from BestOperator import views
from BestOperator.views import MainView

urlpatterns = [
    url(r'^r/$', views.post_results, name='results'),
    url(r'^$', MainView.as_view(), name='index'),
]

main/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^', include('BestOperator.urls', namespace='boo')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BestOperator/forms.py
from django import forms
from django.contrib import admin
from django.forms import models
from BestOperator.models import Offer, Package, Feature, Payment, \
    DescriptionModel
from django.contrib.admin.widgets import RelatedFieldWidgetWrapper
from django.utils.translation import ugettext_lazy as _

def add_related_field_wrapper(form, col_name):
    rel = form.Meta.model._meta.get_field(col_name).rel
    form.fields[col_name].widget = RelatedFieldWidgetWrapper(
        form.fields[col_name].widget, rel, admin.site,
        can_add_related=True, can_change_related=True)

class SmallLinkForm(forms.ModelForm):
    link = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows':2, 'cols':80}))
    class Meta:
        model = DescriptionModel
        fields = models.ALL_FIELDS

class FeatureForm(forms.ModelForm):#TODO why help text is not displayed?
    offer = forms.ModelChoiceField(queryset=Offer.objects.all(), required=False)
    package = forms.ModelChoiceField(queryset=Package.objects.all(), required=False)
    def __init__(self, *args, **kwargs):
        super(FeatureForm, self).__init__(*args, **kwargs)
        add_related_field_wrapper(self, 'offer')
        add_related_field_wrapper(self, 'package')
    def clean(self):
        cleaned_data = super(FeatureForm, self).clean()
        package = cleaned_data.get("package")
        offer = cleaned_data.get("offer")

        msg = None
        if package is None and offer is None:
            msg = _("Neither package nor offer field value was specified.")
        if package is not None and offer is not None:
            msg = _("Only one of package or offer fields should be populated.")
        if msg:
            self.add_error('package', msg)
            self.add_error('offer', msg)
    class Meta:
        model = Feature
        fields = models.ALL_FIELDS

class PaymentForm(forms.ModelForm):
    offer = forms.ModelChoiceField(queryset=Offer.objects.all(), required=False)
    feature = forms.ModelChoiceField(queryset=Feature.objects.all(), required=False)
    def __init__(self, *args, **kwargs):
        super(PaymentForm, self).__init__(*args, **kwargs)
        add_related_field_wrapper(self, 'offer')
        add_related_field_wrapper(self, 'feature')
    def clean(self):
        cleaned_data = super(PaymentForm, self).clean()
        feature = cleaned_data.get("feature")
        offer = cleaned_data.get("offer")

        msg = None
        if feature is None and offer is None:
            msg = _("Neither feature nor offer field value was specified.")
        if feature is not None and offer is not None:
            msg = _("Only one of feature or offer fields should be populated.")
        if msg:
            self.add_error('feature', msg)
            self.add_error('offer', msg)
    class Meta:
        model = Payment
        fields = models.ALL_FIELDS

BestOperator/views.py
from django.template import RequestContext
from django.views.generic import TemplateView
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from BestOperator.funcs import MagicSql
from BestOperator.models import Operator, ServiceType
from django.utils.translation import ugettext_lazy as _


class MainView(TemplateView):
    template_name = "BestOperator/index.html"

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        context['operators'] = Operator.objects.all()
        context['serviceTypes'] = ServiceType.objects.filter(is_displayed=True)
        return context

def post_results(request):
    if (request.method!='POST'):
        return HttpResponseRedirect(reverse('boo:index'))
    try:#TODO make not all parameters required. Basically we could run this without any params at all
        # 1) get input:
        #   get source operator preferences: mts, kyivstar, life; - percentage; sum of the criteria values should be 100%
        #   get target operator preferences: mts, kyivstar, life; - percentage; sum of the criteria values should be 100%
        #   get target usage preferences: data, sms, calls, international calls? - percentage; sum of the criteria values should be 100%
        #   get money preferences: what is monthly limit for you (slider) - integer, "0" by default, this means "no limit"
        fromOperators = Operator.objects.filter(pk=request.POST['from_operators'])
        toOperators = Operator.objects.filter(pk=request.POST['to_operators'])
        preferredServices = ServiceType.objects.filter(pk=request.POST['pref_services'])
        moneyLimit = request.POST['money_limit']
    except (KeyError, Operator.DoesNotExist, ServiceType.DoesNotExist):
        # Redisplay the question voting form.
        context = RequestContext(request, {
            'error_message': _("You didn't make your choice"),
        })
        return render(request, 'BestOperator/index.html', context)#TODO HttpResponseRedirect
    else:
        sql = 'select  ' \
        '    o.name as oper_name' \
        '    , o.link as oper_link' \
        '    , p.id as pack_id' \
        '    , p.name as pack_name' \
        '    , p.description as pack_descr' \
        '    , round(p.price, 0) as pack_price' \
        '    , p.link as pack_link' \
        '    , pf.id as pack_feature_id' \
        '    , ps.name as pack_service_name' \
        '    , pst.name as pack_service_type' \
        '    , off.name as offer_name' \
        '    , s.name as service_name' \
        '    , st.name as st_name' \
        ' from  ' \
        '    bestoperator_operator o' \
        '    join bestoperator_package p on p.operator_id = o.id' \
        '    left join bestoperator_feature pf on pf.package_id = p.id' \
        '    left join bestoperator_service ps on pf.service_id = ps.id' \
        '    left join bestoperator_servicetype pst on pst.id = ps.service_type_id' \
        '    left join bestoperator_offer_package oftp on oftp.package_id = p.id' \
        '    left join bestoperator_offer off on oftp.offer_id = off.id' \
        '    left join bestoperator_feature f on f.offer_id = off.id' \
        '    left join bestoperator_service s on f.service_id = s.id' \
        '    left join bestoperator_servicetype st on st.id = s.service_type_id' \
        ' order by o.name, p.name'
        sqlRows = MagicSql(sql).get_named_tuple()
        # 2) make calculations:
        #   this would be just one multi-table join SQL query
        #       input parameters filtering list will be concatenated as dynamic SQL at runtime just BEFORE script execution.
        #       get value of how valuable each criteria is (%)
        #   select list of packages which are most valuable:
        #       each package has features. Each feature should have "how good" value assigned
        #       this assigned value will be multiplied on target %
        #       all package criteria resulting values should be summarized
        #   packages should be sorted by this resulting sum
        #   results should be represented as list of rows - 1 row for the separate package to output
        context = RequestContext(request, {
            'sqlRows': sqlRows,
        })
        # 3) output data:
        #   output packages on the results page
        #   use the same template as for data input (only difference is - pass resulting table parameter to template)
        #   packages to be grouped inside of the template (it is cheep operation, because little amount of packages to be shown on the page)
        #   table headers will be transposed to row names (this will be the feature names) in the resulting page
        #   each table row will be transposed to separate column with 1 package in it
        return render(request, 'BestOperator/results.html', context)#TODO HttpResponseRedirect

BestOperator/templates/BestOperator/index.html
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	{% load i18n %}
    <meta name="Description" content="{% blocktrans %}Select best operator in Ukraine. Save on mobile right away. This is free. Operators: life:), MTC, Kyivstar{% endblocktrans %}"/>
    <meta name="keywords" content="{% blocktrans %}Select operator, most-suitable package, optimal package, profitable operator, MTC, MTS, Kyivstar, Life, Life:){% endblocktrans %}">
    <meta name="author" content="Данко Inc ©">
    <meta name="application-name" content="Best Operator Online - Boo">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
    <title>{% trans 'Best Operator' %}</title>
    {% load staticfiles %}
    <!-- Latest compiled and minified CSS -->
    <link href="/static/custom.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<form id='store_data' method='POST' action="{% url 'boo:results' %}" class="main-form">
        <h4 class="text-center">{% trans 'Please make you selection to start searching' %}</h4>
        {% if error_message %}<div class="alert alert-danger" role="alert">{{ error_message }}</div>{% endif %}
		{% csrf_token %}
        <div class="form-group inner-form">
            <label for="from_operators_group"><span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
                {% trans 'Preferred operators:' %}</label>
            <div id="from_operators_group">
                {% for operator in operators %}
                    <label class="checkbox-inline"><input type="checkbox" {% if forloop.first %}checked{% endif %} id="from_operators_{{ operator.id }}" name="from_operators" value="{{ operator.id }}">{{ operator.name }}</label>
                {% endfor %}
            </div>
		</div>
        <div class="form-group inner-form">
            <label for="to_operators_group"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                {% trans 'Preferred directions:' %}</label>
            <div id="to_operators_group">
                {% for operator in operators %}
                    <label class="checkbox-inline"><input type="checkbox" {% if forloop.first %}checked{% endif %} id="to_operators_{{ operator.id }}" name="to_operators" value="{{ operator.id }}">{{ operator.name }}</label>
                {% endfor %}
            </div>
		</div>
        <div class="form-group inner-form">
            <label for="pref_services_group"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                {% trans 'Interested in services:' %}</label>
            <div id="pref_services_group">
                {% for st in serviceTypes %}
                    <label class="checkbox-inline"><input type="checkbox" {% if forloop.first %}checked{% endif %} id="pref_services_{{ operator.id }}" name="pref_services" value="{{ st.id }}">{{ st.name }}</label>
                {% endfor %}
            </div>
		</div>
        <div class="form-group inner-form">
            <label for="money_limit_group"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                {% trans 'Max price (per month):' %}</label>
            <div id="money_limit_group">
                <div class="input-group">
                  <span class="input-group-addon">{% trans 'UAH' %}</span>
                  <input type="text" class="form-control" aria-label="{% trans 'Price (rounded to whole UAH)' %}" value="0" id="money_limit" name="money_limit">
                  <span class="input-group-addon">.00</span>
                </div>
            </div>
		</div>
        <button class="btn btn-default submit-button" type="submit" rel="nofollow">{% trans 'GO!' %}</button>
	</form>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/static/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

BestOperator/templates/BestOperator/results.html
<html><!--glyphicon glyphicon-bookmark-->
    {% load bestoperator_extras %}
    <body>
        <table border="1" cellspacing="0">
            <thead><tr><td>&nbsp</td>
                {% for col in sqlRows|row_data:"oper_name, oper_link" %}
                    <td><a href="{{ col|gv:"oper_link" }}">{{ col|gv:"oper_name" }}</a></td>
                {% endfor %}</tr>
            </thead>
            <tbody>
                <tr><td>Пакет і посилання</td>
                    {% for col in sqlRows|row_data:"pack_name, pack_link" %}
                        <td><a href="{{ col|gv:"pack_link" }}">{{ col|gv:"pack_name" }}</a></td>
                    {% endfor %}
                </tr>
                <tr><td>Опис</td>
                    {% for col in sqlRows|row_data:"pack_descr" %}
                        <td>{{ col }}</td>
                    {% endfor %}
                </tr>
                <tr><td>Ціна</td>
                    {% for col in sqlRows|row_data:"pack_price" %}
                        <td>{{ col }}</td>
                    {% endfor %}
                </tr>
                <tr><td>Ціна</td>
                    {% for col in sqlRows|row_data:"pack_feature_id" %}
                        <td>{{ col }}</td>
                    {% endfor %}
                </tr>
                <tr><td>Послуга пакета</td>
                    {% for col in sqlRows|row_data:"pack_service_name" %}
                        <td>{{ col }}</td>
                    {% endfor %}
                </tr>
                <tr><td>Тип послуги пакету</td>
                    {% for col in sqlRows|row_data:"pack_service_type" %}
                        <td>{{ col }}</td>
                    {% endfor %}
                </tr>
                <tr><td>Пропозиція</td>
                    {% for col in sqlRows|row_data:"offer_name" %}
                        <td>{{ col }}</td>
                    {% endfor %}
                </tr>
                <tr><td>Сервіс</td>
                    {% for col in sqlRows|row_data:"service_name" %}
                        <td>{{ col }}</td>
                    {% endfor %}
                </tr>
                <tr><td>Тип сервісу</td>
                    {% for col in sqlRows|row_data:"st_name" %}
                        <td>{{ col }}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
        <h1>SQL DATA:</h1>
    <table border="1">
        {% for row in sqlRows %}<tr>
            {% for col in row %}<td>{{ col }}</td>
            {% endfor %}</tr>
        {% endfor %}</table>
    </body>
</html>